{
 "title": "Project Dashboard",
 "description": "Дашборд для сервиса предсказания цен для объектов недвижимости",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов и ошибок",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "main_app_predictions_count", "legendFormat": "Все запросы" },
    {
     "expr": "main_app_counter_errors_total{}",
     "legendFormat": "Запросы с ошибками"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Рост количества запросов и ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(main_app_counter_errors_total[1m])",
     "legendFormat": "Запросы с ошибками"
    },
    {
     "expr": "increase(main_app_predictions_count[1m])",
     "legendFormat": "Все запросы"
    }
   ]
  },
  {
   "title": "Квантили предсказаний модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "0.5-ая квантиль (медиана)"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "0.95-ая квантиль"
    },
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "0.05-ая квантиль"
    }
   ]
  }
 ]
}