services:
  main-app:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile_ml_service
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /models
    hostname: fastapi_app

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROM_PORT}:${PROM_PORT}"
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    hostname: prometheus

  grafana:
    image: grafana/grafana
    env_file:
    - ./.env
    ports:
    - "${GRAF_PORT}:${GRAF_PORT}"
    environment:
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}